//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckoutTests.CheckoutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CheckoutService.ICheckout")]
    public interface ICheckout {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckout/Scan", ReplyAction="http://tempuri.org/ICheckout/ScanResponse")]
        void Scan(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckout/Scan", ReplyAction="http://tempuri.org/ICheckout/ScanResponse")]
        System.Threading.Tasks.Task ScanAsync(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckout/GetTotalPrice", ReplyAction="http://tempuri.org/ICheckout/GetTotalPriceResponse")]
        int GetTotalPrice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckout/GetTotalPrice", ReplyAction="http://tempuri.org/ICheckout/GetTotalPriceResponse")]
        System.Threading.Tasks.Task<int> GetTotalPriceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICheckoutChannel : CheckoutTests.CheckoutService.ICheckout, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckoutClient : System.ServiceModel.ClientBase<CheckoutTests.CheckoutService.ICheckout>, CheckoutTests.CheckoutService.ICheckout {
        
        public CheckoutClient() {
        }
        
        public CheckoutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckoutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckoutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckoutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Scan(string item) {
            base.Channel.Scan(item);
        }
        
        public System.Threading.Tasks.Task ScanAsync(string item) {
            return base.Channel.ScanAsync(item);
        }
        
        public int GetTotalPrice() {
            return base.Channel.GetTotalPrice();
        }
        
        public System.Threading.Tasks.Task<int> GetTotalPriceAsync() {
            return base.Channel.GetTotalPriceAsync();
        }
    }
}
